- hosts: localhost
  vars_prompt:
    - name: "shell_rc_raw"
      prompt: "Please enter the path to your shell config file"
      private: no
      default: "~/.bash_profile"
  vars:
    ruby_version: 2.5.1
    homedir: "{{ '~' | expanduser }}"
    shell_rc: "{{ shell_rc_raw | expanduser }}"
    ssh_config: "{{ homedir }}/.ssh/config"
  environment:
    HOMEBREW_NO_INSECURE_REDIRECT: 1
    HOMEBREW_CASK_OPTS: --require-sha
    PATH: "/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:{{ ansible_env.PATH }}"
    GOPATH: "{{ homedir }}/go"
    WORKING_ROOT: "{{ homedir }}/wrk"

  roles:
    - mac-laptop
