- name: Check if aws cli config file exists
  stat:
    path: "{{ aws_cli_config }}"
  register: aws_cli_config_stat_result

- name: Ensure that AWSCLI config file exists
  file:
    path: "{{ aws_cli_config }}"
    state: touch
  when: not aws_cli_config_stat_result.stat.exists

- name: Download awscliv2 installer.
  get_url:
    url: https://awscli.amazonaws.com/AWSCLIV2.pkg
    dest: ./AWSCLIV2.pkg
  register: awscli_installer

- name: Check if AWSCLI installer package exists
  stat:
    path: "{{ awscli_installer }}"
  register: awscli_installer_stat_result

- name: Clean up AWSCLI installer package
  file:
    # path: "{{ awscli_installer }}"
    path: AWSCLIV2.pkg
    state: absent
  # when: awscli_installer_stat_result.stat.exists

- name: Run the installer.
  command:
  args:
    cmd: "installer -pkg AWSCLIV2.pkg -target /"
  become: true
  register: aws_install
  when: awscli_installer_stat_result.stat.exists

- name: "Show installer output."
  debug:
    var: aws_install
    verbosity: 2
